# -*- coding: utf-8 -*-
# Catalogo generado a partir de base_para__QR.xlsx (categorias, clasificaciones y proveedores)
# Se usa SOLO para generar numero_parte / QR de refacciones NUEVAS.
# No modifica ni sustituye las refacciones ya existentes en la base de datos.

CATEGORIAS = {
    "100": {
        "nombre": "AD-PACK",
        "clasificaciones": {
            "100": "PLASTA",
            "200": "OTROS",
            "300": "PRODUCCION INTERNA",
            "400": "ACTIVOS",
            "900": "HERRAMIENTAS"
        }
    },
    "200": {
        "nombre": "3M",
        "clasificaciones": {
            "100": "ADHESIVOS",
            "200": "ABRASIVOS",
            "300": "CINTAS",
            "400": "MASKING",
            "500": "PAÑOS",
            "600": "EPP",
            "700": "OTROS",
            "800": "FILTROS",
            "900": "HERRAMIENTAS"
        }
    },
    "300": {
        "nombre": "OTROS",
        "clasificaciones": {
            "100": "ABRASIVOS",
            "200": "CARTON",
            "300": "CINTAS",
            "400": "EMBALAJE",
            "500": "PLASTICOS",
            "600": "LIJAS",
            "700": "REFACCIONES EQUIPOS",
            "800": "OTROS",
            "900": "HERRAMIENTAS"
        }
    },
    "400": {
        "nombre": "TUK",
        "clasificaciones": {
            "100": "C. EMPAQUE",
            "200": "C. MARCAJE",
            "300": "C.ENMASCARAR",
            "400": "C.DOBLE CARA",
            "500": "C. MULTIUSOS",
            "600": "MASKING",
            "700": "C. OTROS",
            "900": "HERRAMIENTAS"
        }
    },
    "500": {
        "nombre": "EMBALAJE",
        "clasificaciones": {
            "100": "BOLSAS",
            "200": "POLIFOAM",
            "300": "CINTAS",
            "400": "CARTON",
            "500": "FLEJES",
            "600": "STRECH FILM",
            "700": "POLIBURBUJAS",
            "800": "PLASTICO",
            "900": "HERRAMIENTAS"
        }
    },
    "600": {
        "nombre": "TERMO",
        "clasificaciones": {
            "100": "PET",
            "200": "PRODUCTO TERMINADO",
            "300": "MATERIA PRIMA",
            "900": "HERRAMIENTAS"
        }
    },
    "700": {
        "nombre": "CONVER",
        "clasificaciones": {
            "100": "MATERIA PRIMA",
            "200": "MATA",
            "300": "NISSAN",
            "400": "PRODUCTOS CONVERTIDOS",
            "900": "HERRAMIENTAS"
        }
    },
    "800": {
        "nombre": "MANTENIMIENTO",
        "clasificaciones": {}
    },
    "900": {
        "nombre": "DISPONIBLE",
        "clasificaciones": {}
    }
}

PROVEEDORES = {
    "A1": "3M COMPANY",
    "A2": "3M MEXICO, S.A. DE C.V.",
    "A3": "ABASTECEDORA LUMEN",
    "A4": "ABRASIVOS Y ADHESIVOS DE NEUCALPAN",
    "A5": "ABRASIVOS Y CONVERSIONES IDEAL, S.A. DE C.V.",
    "A6": "ACAT MAXICANA S.A. DE C.V.",
    "A7": "ADMINISTRADORA GALLCO",
    "A0": "ADPACK",
    "A8": "ADVANCED COMPOSITES MEXICANA S.A. DE C.V.",
    "A9": "ALEJANDRO BALCAZAR LOPEZ",
    "B0": "ANTONIO ESQUIVEL HERRERA",
    "B1": "ARGAL CONSULTORIA E INGENIERIA EN SISTEMAS DE BOMBEO",
    "B2": "ARTURO ISAAC LOPEZ MERCADO",
    "B3": "AUTOMATIZACION, TECNOLOGIA Y CONTROL",
    "B4": "AUTOZONE DE MEXICO",
    "B5": "AVIMACK DE MEXICO",
    "B6": "BANDAS Y MANGUERAS EL CAMINO",
    "B7": "BICICLETAS ARELLANO",
    "B8": "BODEGA DE PAPEL MESONES",
    "B9": "BOLSAS ARTESANALES DE OCCIDENTE S.A. DE C.V.",
    "C0": "BRUNO TLALOLINI MAÑON",
    "C1": "CARLOS GERMAN RIVERA VALENCIA",
    "C2": "CARLOS GONZALEZ REYNOSO",
    "C3": "CARLOS ORTIZ JIMENEZ",
    "C4": "CARTOESPECIALIZADOS MONTERREY, S.A. DE C.V.",
    "C5": "CARTON Y CAJAS DEL NORTE",
    "C6": "CASA MYERS",
    "C7": "CLAUDIA ERIKA JIMENEZ LUEVANO",
    "C8": "CNR INDUSTRIES DE MEXICO",
    "C9": "COMERCIALIZADORA JHIRE, S.A. DE C. V.",
    "D0": "COMERCIALIZADORA MEXRELEASE",
    "D1": "CONEXIONES Y MANGUERAS HIDROCALIDAS",
    "D2": "CONVERPET GROUP",
    "D3": "CORIBA Y CORNEJO S DE RL DE CV",
    "D4": "COROZEN SA DE CV",
    "D5": "COSTCO DE MEXICO",
    "D6": "DAYTON PROGRESS",
    "D7": "DCA ELECTRONICS",
    "D8": "DDA SEGURIDAD INDUSTRIAL",
    "D9": "DISTRIBUIDORA ASTON",
    "E0": "DISTRIBUIDORA TOOLCOMEX",
    "E1": "DOXA",
    "E2": "EDUARDO COMTE VILLALOBOS",
    "E3": "EL SURTIDOR",
    "E4": "ELTON PROMOCIONES Y EMBALAJE, S.A. DE C.V.",
    "E5": "EMPAQUES, MAQUILAS Y SERVICIOS DE AGUASCALIENTES",
    "E6": "ENERGIA OPTIMA",
    "E7": "EQUIPOS Y CONTROL DE FLUIDOS",
    "E8": "EUGENIA MARIA ELENA VILLALPANDO VELAZQUEZ",
    "E9": "EXCELCUTS S DE R.L DE C.V",
    "F0": "EXCELCUTS S. DE R.L. DE C.V.",
    "F1": "FERRETERIA KIMURA S.A. DE C.V.",
    "F2": "FERRETERIA LA PASIEGA",
    "F3": "FRANCISCO JAVIER GARCIA GONZALEZ",
    "F4": "FURA, S.A. DE C.V.",
    "F5": "GABRIEL CASTAÑEDA MEDINA",
    "F6": "GLORIA HERLINDA SENCION BAZUA",
    "F7": "GP ELECTROMECANICA S.A. DE C.V.",
    "F8": "GRAINGER MARKET",
    "F9": "GRUPO COMERCIAL ACOMEE",
    "G0": "GRUPO LEMOND",
    "G1": "GSIDEMIND S.A DE C.V",
    "G2": "GUANTES INDUSTRIALES DE MEXICO",
    "G3": "HERRAMIENTAS ACZ",
    "G4": "HERRAMIENTAS GEMELO",
    "G5": "HOME DEPOT MEXICO",
    "G6": "IGUS MEXICO",
    "G7": "INDUSTRIAS NOTESA, S.A. DE C.V.",
    "G8": "INDUSTRIAS ORJI, S.A. DE C.V.",
    "G9": "INDUSTRIAS RASSA S.A. DE C.V.",
    "H0": "INDUSTRIAS TUK, S.A. DE .C.V.",
    "H1": "INFINITY INDUSTRIAL EQUIPMENT",
    "H2": "INSUMOS CONTENEDORES PLASTICOS",
    "H3": "JORGE LUIS AYALA NUÑEZ",
    "H4": "JOSE LUIS OCHOA BUSTAMANTE",
    "H5": "JUAN FRANCISCO RUIZ ARIAS",
    "H6": "JUAN VICTOR MARTINEZ LOPEZ",
    "H7": "KERIGMA COMERCIALIZADORA",
    "H8": "KNOVA",
    "H9": "LA PALOMA COMPAÑIA DE METALES",
    "I0": "LA PALOMA COMPAÑIA DE METALES SA DE CV",
    "I1": "LAMINADOS EXTRUIDOS PLASTICOS",
    "I2": "LIMSA",
    "I3": "LUGO CASTRO Y COMPAÑIA",
    "I4": "LUIS FERNANDO VILLALOBOS GONZALEZ",
    "I5": "MAGNETIKA SAIFFE SA DE CV",
    "I6": "MANUFACTURARA DE CINTAS ADHESIVAS, S.A. DE C.V",
    "I7": "MARCHAND",
    "I8": "MARCO ANTONIO MORALES PADILLA",
    "I9": "MARIZOL HERMOSILLO VELASCO",
    "J0": "MARPOSS S.A. DE C.V.",
    "J1": "MARTHA PATRICIA JIMENEZ MUÑOZ",
    "J2": "MARTHA VELAZQUEZ TISCAREÑO",
    "J3": "MERCADO PANDA",
    "J4": "MERCANTIL CORMA",
    "J5": "MEXITRADE Y SERVICIOS EMPRESARIALES",
    "J6": "MULTIHERRAMIENTAS DEL BAJIO",
    "J7": "MULTIMARCAS TRALI S.A. DE C.V.",
    "J8": "NEO PELICULAS",
    "J9": "NORDSON MEXICO",
    "K0": "OFFICE DEPOT DE MEXICO",
    "K1": "OFFICEMAX",
    "K2": "OFIMART DEL CENTRO",
    "K3": "OFIX",
    "K4": "OPTIMOPLAS Y FLEJES S.A. DE C.V.",
    "K5": "OSHITANI INDUSTRIAL MEXICANA S. DE R.L. DE C.V.",
    "K6": "OSUNA BALERO DISTRIBUIDOR",
    "K7": "PACK TRADE LATINOAMERICA",
    "K8": "PAPELERIA HERRERA CORNEJO DE OCCIDENTE",
    "K9": "PBI PLASTIC GROUP SA DE CV",
    "L0": "PLASTICOS CAM",
    "L1": "PLASTICOS DE INGENIERIA TECNOQUIM SA DE CV",
    "L2": "PNEUMATECNIA",
    "L3": "POWER DEPOT",
    "L4": "PRODUCTOS Y PIEZAS ESPECIALES",
    "L5": "PSM AUTOMOTIVE",
    "L6": "QUANTUM",
    "L7": "RAFAEL RAMOS PICAZO",
    "L8": "REFACCIONARIA ROGELIO",
    "L9": "RODAMIENTOS Y ACCESORIOS",
    "M0": "RODAMIENTOS Y REFACCIONES AUTOMOTRICES E INDUSTRIALES JOGAR",
    "M1": "ROSIO MACIEL GUZMAN",
    "M2": "SERGIO ARMANDO QUEZADA ARAUJO",
    "M3": "SERVICIOS DE FRONTERA DEHP",
    "M4": "SERVICIOS OPERATIVOS GRIVER",
    "M5": "SERVICIOS TECNICOS PROFESIONALES DE AGUASCALIENTES",
    "M6": "SHURTAPE MEXICO, S. DE R.L. DE C.V.",
    "M7": "SIMPLE Y DIRECTO",
    "M8": "SINGLE CORRUGADOS, S.A. DE C.V.",
    "M9": "SINTEPLAST, S.A DE C.V",
    "N0": "SISTEMAS DE ALMACENAMIENTO",
    "N1": "SOLUCIONES EN ILUMINACION",
    "N2": "SOLUCIONES ENFOCADAS",
    "N3": "SUMINISTROS EN METROLOGIA",
    "N4": "TIENDA MERCADAZO S.A. DE C.V.",
    "N5": "TM DE AMERICA, S.A DE C.V.",
    "N6": "TODO EN CAJA, S.A. DE C.V.",
    "N7": "TOYO KASEI",
    "N8": "TRENZADOS MARINOS",
    "N9": "TWILIGHT INSTRUMENTOS DE MEDICION INDUSTRIAL",
    "Ñ0": "UNLINE SHIPPING SUPPLIES S DE RL DE CV",
    "Ñ1": "VALVULAS CONTROLES Y SERVICIOS",
    "Ñ2": "VIRIDIANA NATALY JUAREZ SALGADO",
    "Ñ3": "WIRBEL EQUIPOS INDUSTRIALES",
    "Ñ4": "WORLDWIDE FOAM, S. DE R.L. DE C.V.",
    "Ñ5": "YAMAZEN MEXICANA"
}
